# Generated by Django 3.1 on 2020-08-24 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_contact_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='timeStamp',
            new_name='time_stamp',
        ),
    ]
