# Generated by Django 3.1 on 2022-06-24 12:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20220624_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='time_stamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
